spring:
  application:
    name: mssistemalanchonete
  datasource:
    driverClassName: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
  sql:
    init:
      continue-on-error: true
server:
  port: 8080
  servlet:
    context-path: /sistema-lanchonete/api/v1
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html

