spring:
  jpa:
    show-sql: true
  sql:
    init:
      continue-on-error: true
  
SPRING_DATASOURCE_USERNAME: user
SPRING_DATASOURCE_PASSWORD: password
SPRING_JPA_HIBERNATE_DDL_AUTO: update
SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/lanchonete
