apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistema-lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: app-lanchonete
          image: guimaj/sistema-lanchonete:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-database
                  key: database_url
